services:
  client:
    image: ${IMAGE_NAME}-client:latest
    ports:
      - "8080:9090"
    deploy:
      replicas: 1


  server:
    image: ${IMAGE_NAME}-server:latest
    ports:
      - "3000:3000"
    deploy:
      replicas: 1