---
- hosts: TestDevServer

  tasks:
    - name: Kill all
      command: docker kill $(docker ps -q)

    - name: Remove all containers
      command: docker rm $(docker ps -a -q)

    - name: Remove all images
      command: docker rmi -f $(docker images -aq)

    - name: Start the Client Docker container
      command: docker run -d --name fe-container -p 8080:8080 benhuhaudau/rmit-store-client

    - name: Start the Server Docker container
      command: docker run -d --name be-container -p 3000:3000 benhuhaudau/rmit-store-server

    - name: Wait for the client container to be ready
      shell: |
        until docker exec fe-container ls /app; do
          sleep 2
        done

    - name: Wait for the server container to be ready
      shell: |
        until docker exec be-container ls /app; do
          sleep 2
        done

    # - name: Copy test output to control machine
    #   fetch:
    #     src: /tmp/test_output.txt
    #     dest: /tmp/jenkins/test_output.txt
    #     flat: yes

    # - name: Copy test exit code to control machine
    #   fetch:
    #     src: /tmp/test_exit_code.txt
    #     dest: /tmp/jenkins/test_exit_code.txt
    #     flat: yes

    # - name: Stop and remove the container
    #   shell: |
    #     docker stop fe-container
    #     docker rm fe-container
